name: Build & upload Short

on:
  schedule:
    - cron:  '0 17 * * *'      # 17:00 UTC = 19:00 Europe/Rome
  workflow_dispatch:           # pulsante “Run workflow”

jobs:
  build:
    runs-on: ubuntu-latest
    concurrency: short_factory

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: System deps
        run: sudo apt-get update && sudo apt-get install -y ffmpeg

      - name: Install Python deps
        run: pip install -r requirements.txt

      - name: Re-create OAuth file
        env:
          YT_CLIENT_SECRET_JSON: ${{ secrets.YT_CLIENT_SECRET_JSON }}
        run: |
          echo "$YT_CLIENT_SECRET_JSON" | base64 -d > client_secret.json

      - name: Generate & upload Short
        env:
          OPENAI_API_KEY:      ${{ secrets.OPENAI_API_KEY }}
          PEXELS_API_KEY:      ${{ secrets.PEXELS_API_KEY }}
          ELEVENLABS_API_KEY:  ${{ secrets.ELEVENLABS_API_KEY }}
          YT_REFRESH_TOKEN:    ${{ secrets.YT_REFRESH_TOKEN }}
        run: python faceless_short_automation.py
